- menu_name: "Services"

- name: "Contact"
  url: "https://github.com/dkpro/dkpro-csniper/graphs/contributors"
  class: "services-contact"
  title: "Contact"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  class: "sitemap-link"
  title: "Sitemap for Google Webmastertools"
